- test/schema/data.json
> fix(schema): add missing sections

- package-lock.json
- package.json
- script/build-task.js
> Add Package Manifest+ flags

- CONTRIBUTING.md
- MODULE_README.md
- README.md
- script/build-task.js
> feat(readme): move module readme to README.md; split out dev notes

- CONTRIBUTING.md
- README.md
- tool/public/client.js
- tool/public/index.html
Primarily expanding/rewriting `README.md` and `CONTRIBUTING.md` so The Public™ can understand what's going on. Comments/edits/critique on that are welcome, of course.
Additionally, the web tool got the following upgrades:
- Now loads Foundry `.db` files (converts to JSON on the fly)
- Errors are displayed in the output panel in addition to the console
- The Copy button displays a temporary checkmark when clicked
**Note:** the JS linter appears to not like an escaped `/` (see `client.js#23`), but it is required or the regex won't work. I leave it to you to either ignore/alter the linter, or somehow change the code to not require regex.
> Prettification

- .github/workflows/push-master.yaml
- package-lock.json
- package.json
> Automated builds

- .github/workflows/push-master.yaml
- package-lock.json
- package.json
Now that the automated build works, it's time to break it
> Add version message body

- .github/workflows/push-master.yaml
- package-lock.json
- package.json
thank you `zip` very intuitive
> Zip from correct directory

- .github/workflows/push-master.yaml
- package-lock.json
- package.json
> Output zip to correct dir

- macro-item/spell/XGE_toll-the-dead.js
- module/data/spell/GiddySpell.json
- module/data/spell/__core.json
- module/js/Main.js
- module/shared/SharedConsts.js
- package-lock.json
- package.json
- script/build-task.js
- script/package.js
- test/schema/shared.json
- test/test-json.js
Abandons v9 support in favour of v10.
> v10 support

- module/data/spell/__core.json
> fix(spell): use correct data/system property in Aid

- module/data/optionalfeature/BST.json
Can you guess which 3 I'm using?
> Add effects for some Beastheart Primal Exploits

- CONTRIBUTING.md
- README.md
If it's wrong, then why does it feel soright?
> Use "Addon" over "Add-on"

- macro-item/spell/PHB_aura-of-vitality.js
[Credit to Szefo09](https://discord.com/channels/363680385336606740/555058648536055830/1071231570792419328) 
These don't need to be optional chained because we require midi-qol to begin with
> fix(spell): fix aura of vitality cast level

- README.md
Adds the manifest URL to the readme for ease of installation
> doc(Readme): Add manifest URL to homepage

- meta/changelog.json
- package-lock.json
- package.json
- script/generate-changelog.js
- test/test-json.js
- test/test-preversion-changelog.json.js
> Move to JSON changelog; automate changelog check/generation on versioning

- README.md
- module/data/classFeature/__core.json
- module/data/item/__core.json
- module/data/spell/__core.json
- module/data/subclass/__core.json
- module/js/DataManager.js
- script/build-task.js
- script/generate-optional-dependencies.js
- test/schema/shared.json
This removes itemacro as a hard dependency.
> Add "requires" to "itemMacro" declarations; filter by requirements

- module/js/DataManager.js
This is required as when loading some importers (e.g. the Class Features
importer), Plutonium eagerly pulls in side-data, and by extension, our
addon data. This triggers a junk "could not import X because of bad
requirements" message.
> Add "isSilent" flag to API which squashes notifications

- module/js/DataManager.js
Including embedded-CEs-in-embedded-items, i.e. spells.
> Avoid crash when Quick Inserting actor with embedded CEs

- module/js/Api.js
- module/js/Main.js
- module/js/OptionalDependenciesManager.js
- module/js/SettingsManager.js
- module/js/integrations/ChrisPremades.js
- module/js/integrations/IntegrationBase.js
- module/js/integrations/Integrations.js
- module/js/mixins/MixinStartupHooks.js
This removes some duplication, making it easier to add hooks in a consistent fashion in future.
> Refactor hook bindings to mixin

- script/build-task.js
A dumping ground for commits as I go through the v11 changelogs. Will separate things out more later, probably.
> Support v11

- module/data/classFeature/__core.json
- test/schema/shared.json
Currently, both the custom and the SRD effect are pulled in.
> Ignore SRD Rage effect

- module/data/subclass/__core.json
- module/js/integrations/ChrisPremades.js
Add missing dice scale, and use correct maneuver prefix/aliases.
> Improve Battle Master Fighter support
