- module/data/raceFeature/GiddyRace.json
- module/data/spell/GiddySpell.json
- test/schema/core.json
- test/schema/homebrew.json
- test/schema/shared.json
- test/test-json.js
This demonstrates a simple `_meta` addon which has the "important bits"
of the standard homebrew `_meta`, in a slightly-flattened format (this
is due to each homebrew file in this repo matching exactly one homebrew
`"json"` source, whereas a file in the homebrew repo can contain
multiple `"json"` sources).
We choose to omit the `author`, `url`, etc. properties, as this
information is already stored in the homebrew repo, and duplicating it
has no benefit.
> feat(sample): add `_meta` sections to homebrew files

- .gitignore
- module/data/optionalfeature/__core.json
- module/data/spell/__core.json
- module/data/subclassFeature/__core.json
1) Can be handled by DAE for one less dependency
2) Can cause unexpected problems (e.g. _catnap_ spell); use `about-time` for out-of-combat AE expiry
Ran the `npm t` test and got no problems. Separately, since I'm by no means a node expert, but should I be pushing any changes to `package-lock.json` here? I noticed in the npm documentation it says that it's _intended_ to be committed, but I'm wary of overwriting whatever you have (since many lines were removed in the diff).
> Revert on-rest AE expiry

- module/data/item/__core.json
- test/schema/shared.json
This provides a helpful example of how/why to use this, as the
"flags.dnd5e.initiativeAdv" effect is built in to Plutonium already.
> feat(core): use "_merge" in Sentinel Shield effects

- MODULE_README.md
- module/data/classFeature/__core.json
- module/data/feat/__core.json
- module/data/item/__core.json
- module/data/optionalfeature/__core.json
- module/data/spell/GiddySpell.json
- module/data/spell/WJMAiS.json
- module/data/spell/__core.json
- module/data/subclassFeature/__core.json
- script/build-task.js
- test/schema/shared.json
This set of modules is to be considered the (current) core we build
everything out from. To avoid adding the same requirement to hundreds of
effects/etc., we depend on these three modules at the module level.
> feat(module): add `midi-qol`, `dae`, and `times-up` as hard dependencies

- module/data/spell/__core.json
- module/data/subclassFeature/__core.json
- test/schema/core.json
- test/schema/homebrew.json
- test/schema/shared.json
- tool/public/client.js
Also `$schema` `examples` for ease of use
> test(json): harder enforcement of empty arrays and effect modes, require _meta

- CONTRIBUTING.md
- macro-item/spell/XGE_toll-the-dead.js
- module/data/spell/__core.json
- package-lock.json
- package.json
- script/build-task.js
- script/consts.js
- script/generate-item-macro-template.js
- test/schema/shared.json
Maintain a set of script files, external to the module's core files,
which are baked into the data files at build time. This allows the
scripts to be easily linted/edited with syntax highlighting, and keeps
the human-editable data files junk-free.
Closes #22
> Add item macro support

- module/data/feat/__core.json
- module/data/item/__core.json
- module/data/subclassFeature/__core.json
- test/schema/shared.json
- tool/public/client.js
Plutonium's AE handling, when it comes to compatibility with
MidiQOL/DAE, is currently abysmal. As part of efforts to straighten that
out moving forward, be more explicit about which effects have which
`transfer`/`disabled` values.
Additionally, avoid using MidiQOl-specific versions of these flags, as
they don't seem to take precedence over the real `transfer`/`disabled`,
which Plutonium always sets to a non-null value internally.
Note that for all "addon" effects, the implicit default for both values
is `false`. This also applies to the `foundry-*.json`s/etc. in the
5etools source, so copy-pasting between the two won't require any
changes.
> feat(effects): explicitly set `true` disabled/transfer values

- package-lock.json
- package.json
- script/build-task.js
Locking the "manifest" URL to a specific version prevents the user from
ever updating the module via the "Update" button in Foundry, which is
not ideal.
> Avoid using version'd manifest URLs

- macro-item/spell/PHB_aid.js
- module/data/spell/__core.json
Aid has some controversial behavior, the [top answer](https://rpg.stackexchange.com/a/45345) on RPG Exchange judges that Aid's HP _goes away_ when the spell ends. Also, this HP does not count as healing or temporary HP. Aid's HP pops into existence when the spell is cast, and disappears when the spell ends.
This implementation tries to reflect that interpretation. The maximum HP change is done as a system AE, and the item macro does as little work as possible to increment, and subsequently decrement, the current HP value as described above.
Tested/Working/Linted/etc
> add(spell): Implement Aid

- module/data/classFeature/__core.json
- test/schema/shared.json
This implements the Reckless Attack feature using two AEs:
* Reckless Attack: Grants advantage to the barbarian on strength-based melee attack using midi's `flags.midi-qol.advantage.attack.str` combined with an activation condition, `item.system.actionType == "mwak"`, duration of 1 turn
* Reckless Defense: Grants advantage to attackers using midi's `flags.midi-qol.grants.advantage.attack.all`, duration of 1 round
Reckless Defense specifies a different icon than Reckless Attack (a broken shield) to make it clear to players which expires at the end of the Barbarian's turn. The schema is updated to allow an `img` tag on `foundryEffectObject`s. Obviously this doesn't do anything without support from plut proper.
The effects themselves are tested and work right now, minus the Reckless Defense …
> Implement Reckless Attack

- .github/workflows/release.yaml
The former was set up in order to avoid having release branches, but produces more problems than it solves if multiple people are contributing to the repository. Instead, only build on tagged release versions, whatever branch they happen to be in.
In order to ensure random PRs don't trigger releases, tag protection has now been added to the repo, allowing only admins/maintainers to push version tags.
> feat(build): prefer releasing on tag to releasing on merge to master

- module/data/spell/__core.json
Implement Chill Touch using the same mechanism that midi does, with some cosmetic changes.
Chill Touch is two AEs, one to handle the healing immunity and another to grant attack disadvantage for undead mobs attacking the source token. Both AEs are always applied, the attack disadvantage is gated behind an activation condition.
Because there are two AEs, we have a choice to make with regards to displaying a status icon on the token. Midi sets a false duration on both, displaying the same icon twice. In this PR we set a `statusId` on only the healing immunity, which will cause it to display a status icon. The attack disadvantage is a "passive" AE and while it will persist to the end of the source turn, it will not display status icon.
There could be an argument made for attaching the icon …
> feat(spell): Implement Chill Touch

- macro-item/spell/PHB_aura-of-vitality.js
- module/data/spell/__core.json
Continuing my alphabetical march through the PHB A-spells
Aura of Vitality, despite the name, is not an aura. It's an item summoner. It summons an unnamed item that gives the user the ability to cast a bonus-action 2d6 healing spell within a 30 ft radius for the next 60 seconds.
We fudge this a little bit. We use warpgate to create a a temporary item (cloned from the base Aura of Vitality item, with necessary fields updated appropriately), but we give it a name, "Invoke Vitality". This appears as an At-Will spell on the user's sheet, and sticks around as long as the "Aura" lasts.
The other thing we fudge is range. I set the range of "Invoke Vitality" to 30ft, for simplicity. I think RAW this should be 27.5ft, because technically the 30 ft radius starts at the center of the 5 sqft grid …
> feat(spell): Implement Aura of Vitality

- module/js/Main.js
- test/schema/shared.json
This allows us to avoid specifying all the gory details of a convenient effects effect ourselves.
Allows for refinement of #56
> Add convenient effect shorthand

- macro-item/spell/PHB_aura-of-vitality.js
We shouldn't rely on push/popping the mutation stack.
Thanks to the new [warpgate docs](https://trioderegion.github.io/warpgate/index.html) I learned how to do this correctly and actually attach a name to the mutation that we can use to identify applied mutations.
> fix(spell): Use named mutations for warpgate

- module/data/spell/__core.json
[The Arms. The Arms of Hadar. The Arms chosen specially for Hadar. Hadar's Arms.](https://youtu.be/NcKGw-IO5Uc)
System data is obvious, sets up duration, range, units, and flags in a way that midi understands to do its business.
The effects prop is my preferred way to handle abilities that apply status effects, just throw that bad boy right into the effects array, whole thing. We might want a way to shorthand this that the DataConverter understands and can unpack instead of this approach, perhaps even invoking Dfred's API to get the correct effect data instead of hard coding it into abilities ourselves.
But for now, this works.
> feat(spell): Implement Arms of Hadar

- module/data/spell/__core.json
* Update all references to "data" -> "system"
* Remove rest based special durations on all spells that use it as a substitute for times-up
* Remove Bane, covered in base DND5e
* Remove Barkskin, covered in base DND5e
* Remove Bless, covered in base DND5e
* Remove Blade Ward, covered in base Plut
* Fix Chill Touch, system.traits.di.value -> system.traits.di.custom
* Update Greater Invisibility to use CE shorthand
* Update Invisibility to use CE shorthand
> fix(spell): Update spells for FVTT v10

- tool/public/client.js
- tool/public/index.html
These should generally always be moved to either the site's data or the homebrew repo as appropriate, but having a unified parser here, which filters junk data, is convenient for the time being.
> Add option to keep images when parsing items

- module/js/Main.js
- module/lang/en.json
- module/shared/SharedConsts.js
- module/template/MenuSettingsPrompt.hbs
- script/build-task.js
This shows which settings, in other modules, the user has set to incompatible values, and provides them with a quick-fix button.
In addition, the same dialogue is shown on game load, if incompatible settings are detected (and the user has not disabled the notification).
Closes #17
> Aadd dependency settings check/config dialogue

- macro-item/item/DMG_goggles-of-night.js
- macro-item/item/DMG_lantern-of-revealing.js
- macro-item/item/DMG_mace-of-disruption.js
- macro-item/item/DMG_sword-of-life-stealing.js
- macro-item/item/DMG_sword-of-sharpness.js
- macro-item/item/DMG_sword-of-wounding.js
- macro-item/item/PHB_bullseye-lantern.js
- macro-item/spell/XGE_toll-the-dead.js
- module/data/item/__core.json
- script/build-task.js
- test/schema/core.json
- test/schema/homebrew.json
- tool/public/client.js
MidiQOL's compendium is a bit too junky to use directly, so simply filch the "good" bits.
Additional work to improve tooling, and add support for `magicvariant`s to cut down on item data copy-pasting (this is _partially_ supported in Plutonium currently; full support to be added for next release).
> Add items from the MidiQOL "Sample Items" compendium

- macro-item/spell/XGE_toll-the-dead.js
The level scaling dice was not being edited by the old macro.  This adds a section to resolve this issue.
> Fix level scaling for XGE_toll-the-dead.js

- CONTRIBUTING.md
- README.md
- script/build-task.js
- Remove reference in CONTRIBUTING.md to non-existent Discord channel
- Add additional module conflicts and use them as examples in the README (the v9 examples are mostly dead)
- Reflow some of the README text for easier reading
> Documentation improvements

- README.md
- module/js/DataManager.js
- module/js/Main.js
- module/js/data-source/DataSourceBase.js
- module/js/data-source/DataSourceIntegrations.js
- module/js/data-source/DataSourceSelf.js
- module/js/integrations/ChrisPremades.js
- module/js/integrations/IntegrationBase.js
- module/js/integrations/Integrations.js
- script/build-task.js
This allows PAA to grab item data from CPR, and return it in a format which Plutonium can use. Note if both PAA and CPR have data for an item, then PAA's version takes priority (i.e., the two are *not* merged).
See: https://foundryvtt.com/packages/chris-premades
Closes #86
---
Here's an example of a before/after for Heat Metal
```diff
2c2
<   "name": "Heat Metal (Without)",
---
>   "name": "Heat Metal (With)",
24c24
<       "type": "object"
---
>       "type": "creature"
45c45
<     "chatFlavor": "",
---
>     "chatFlavor": "[2d8 - fire] Use a bonus action on each subsequent turn to cause this damage again",
53c53
<           "2d8",
---
>           "2d8[fire]",
61c61
<       "ability": "con",
---
>       "ability": "",
96a97,136
>     "ddbimporter": {
>       "id": 138066,
> …
```
> Add integration with Chris's Premades

- module/js/Api.js
- module/js/DataManager.js
- module/js/Main.js
- module/js/ModuleSettingConsts.js
- module/js/OptionalDependenciesManager.js
- module/js/SettingsManager.js
- module/js/Util.js
- module/js/integrations/Integrations.js
- module/js/mixins/MixinStartupHooks.js
- module/lang/en.json
This makes it easier to brainlessly smash about and find things which have yet to be automated (although does nothing to handle "false positives," i.e., entities for which no automation is desired), in lieu of, say, a nice tracking system.
> Add an optional warning when importing a non-automated entity 

- module/data/subclassFeature/__core.json
The base property confuses MidiQOL, and so will be removed in next Plutonium release. An alternative has been added under our namespace.
> Use namespace'd `@items` property
